[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.4"
  JEKYLL_ENV = "production"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"
